// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jira-Analyzer/backend-services/internal/service/backend (interfaces: IIssueService,IProjectService)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination mock/mock_service.go . IIssueService,IProjectService
//

// Package mock_backend is a generated GoMock package.
package mock_backend

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Jira-Analyzer/backend-services/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIIssueService is a mock of IIssueService interface.
type MockIIssueService struct {
	ctrl     *gomock.Controller
	recorder *MockIIssueServiceMockRecorder
}

// MockIIssueServiceMockRecorder is the mock recorder for MockIIssueService.
type MockIIssueServiceMockRecorder struct {
	mock *MockIIssueService
}

// NewMockIIssueService creates a new mock instance.
func NewMockIIssueService(ctrl *gomock.Controller) *MockIIssueService {
	mock := &MockIIssueService{ctrl: ctrl}
	mock.recorder = &MockIIssueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIssueService) EXPECT() *MockIIssueServiceMockRecorder {
	return m.recorder
}

// FilterClosedIssues mocks base method.
func (m *MockIIssueService) FilterClosedIssues(arg0 context.Context, arg1 []domain.Issue) []domain.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterClosedIssues", arg0, arg1)
	ret0, _ := ret[0].([]domain.Issue)
	return ret0
}

// FilterClosedIssues indicates an expected call of FilterClosedIssues.
func (mr *MockIIssueServiceMockRecorder) FilterClosedIssues(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterClosedIssues", reflect.TypeOf((*MockIIssueService)(nil).FilterClosedIssues), arg0, arg1)
}

// FilterOpenedIssues mocks base method.
func (m *MockIIssueService) FilterOpenedIssues(arg0 context.Context, arg1 []domain.Issue) []domain.Issue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterOpenedIssues", arg0, arg1)
	ret0, _ := ret[0].([]domain.Issue)
	return ret0
}

// FilterOpenedIssues indicates an expected call of FilterOpenedIssues.
func (mr *MockIIssueServiceMockRecorder) FilterOpenedIssues(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterOpenedIssues", reflect.TypeOf((*MockIIssueService)(nil).FilterOpenedIssues), arg0, arg1)
}

// GetAverageTimeSpent mocks base method.
func (m *MockIIssueService) GetAverageTimeSpent(arg0 context.Context, arg1 []domain.Issue) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageTimeSpent", arg0, arg1)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetAverageTimeSpent indicates an expected call of GetAverageTimeSpent.
func (mr *MockIIssueServiceMockRecorder) GetAverageTimeSpent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageTimeSpent", reflect.TypeOf((*MockIIssueService)(nil).GetAverageTimeSpent), arg0, arg1)
}

// GetIssuesByProject mocks base method.
func (m *MockIIssueService) GetIssuesByProject(arg0 context.Context, arg1 int) ([]domain.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssuesByProject", arg0, arg1)
	ret0, _ := ret[0].([]domain.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuesByProject indicates an expected call of GetIssuesByProject.
func (mr *MockIIssueServiceMockRecorder) GetIssuesByProject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuesByProject", reflect.TypeOf((*MockIIssueService)(nil).GetIssuesByProject), arg0, arg1)
}

// GetWeekAverageCreatedNumber mocks base method.
func (m *MockIIssueService) GetWeekAverageCreatedNumber(arg0 context.Context, arg1 []domain.Issue) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeekAverageCreatedNumber", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWeekAverageCreatedNumber indicates an expected call of GetWeekAverageCreatedNumber.
func (mr *MockIIssueServiceMockRecorder) GetWeekAverageCreatedNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeekAverageCreatedNumber", reflect.TypeOf((*MockIIssueService)(nil).GetWeekAverageCreatedNumber), arg0, arg1)
}

// MockIProjectService is a mock of IProjectService interface.
type MockIProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockIProjectServiceMockRecorder
}

// MockIProjectServiceMockRecorder is the mock recorder for MockIProjectService.
type MockIProjectServiceMockRecorder struct {
	mock *MockIProjectService
}

// NewMockIProjectService creates a new mock instance.
func NewMockIProjectService(ctrl *gomock.Controller) *MockIProjectService {
	mock := &MockIProjectService{ctrl: ctrl}
	mock.recorder = &MockIProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProjectService) EXPECT() *MockIProjectServiceMockRecorder {
	return m.recorder
}

// GetProjectById mocks base method.
func (m *MockIProjectService) GetProjectById(arg0 context.Context, arg1 int) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectById indicates an expected call of GetProjectById.
func (mr *MockIProjectServiceMockRecorder) GetProjectById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectById", reflect.TypeOf((*MockIProjectService)(nil).GetProjectById), arg0, arg1)
}

// GetProjects mocks base method.
func (m *MockIProjectService) GetProjects(arg0 context.Context) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjects", arg0)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjects indicates an expected call of GetProjects.
func (mr *MockIProjectServiceMockRecorder) GetProjects(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjects", reflect.TypeOf((*MockIProjectService)(nil).GetProjects), arg0)
}

// GetProjectsByRange mocks base method.
func (m *MockIProjectService) GetProjectsByRange(arg0 context.Context, arg1, arg2 int) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectsByRange", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectsByRange indicates an expected call of GetProjectsByRange.
func (mr *MockIProjectServiceMockRecorder) GetProjectsByRange(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectsByRange", reflect.TypeOf((*MockIProjectService)(nil).GetProjectsByRange), arg0, arg1, arg2)
}
