db:
  host: "postgres:5432"
  name: "testdb"
  user: "pguser"
  password: "pgpwd"
rest-service:
  host: ":8000"
  connector-host: "connector-service:8003"
  resource-timeout: 5s
  analytics-timeout: 15s
  write-timeout: 15s
  read-timeout: 15s
logger:
  log-file: "logs.log"
  warn-file: "err_logs.log"
